- hosts: localhost
  become: false

  vars:
    user_id: "{{ansible_user_id}}"
  
  tasks:
  - name: Install apt packages
    become: true
    apt: name={{item}}
    with_items:
      - curl
      - git
      - htop
      - kitty
      - zsh

  - name: Set shell to zsh
    become: true
    user:
      name: "{{user_id}}"
      shell: /bin/zsh
  
  - name: Install OMZ
    shell:
      cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
