- hosts: localhost
  become: false

  roles:
    - pre

  vars:
    user_id: "{{ansible_user_id}}"
  
  tasks:
  - name: Install apt packages
    become: true
    apt: name={{item}}
    with_items:
      - curl
      - git
      - htop
      - kitty
      - vim
      - zsh

  - name: Set shell to zsh
    become: true
    user:
      name: "{{user_id}}"
      shell: /bin/zsh

  - name: Setup CLI
    include_role: 
      name: cli
